### ISSUE TITLE
mysqlconnector library not found

### ISSUE THREAD

**Issue by MrHorizonPy** [DanielMartensson/GoobySoft#1]
Hi, when I try to install GoobySoft on Ubuntu, at the moment when I run "cmake -B build ." it returns the error MySQLconnectorC++ not found, although I installed it the library, I also tried running the automatic installation but it returns the same error. What can I do?
I am doing the whole thing on the Raspberry Pi

**Comment by DanielMartensson** [comment]
@MrHorizonPy You need to have the latest MySQL connector. It's not available through `apt-get`. The reason is that MysSQL re-wrote their SQL library to C++ because the old one was full of bugs. The new one, is much better. 

Do you have this folder at your Ubutnu system?

https://github.com/DanielMartensson/GoobySoft/blob/9359aaafa1e742234cf09b3a916cbf3f30192a25/GoobySoft/Tools/Storage/Databases/MySQL/MySQL.cpp#L4-L7

**Comment by MrHorizonPy** [comment]
Yes, I have the MySQL.cpp in the directory and also have the file xdevapi.h in in this path:
/usr/include/mysql_conn-8/mysqlx/xdevapi.h








I also changed the directory in the file:
`#else`
`#include <mysql_conn-8/mysqlx/xdevapi.h>`
`#endif`
`#include <cstdio>`

but doesn't work

**Comment by DanielMartensson** [comment]
> /usr/include/mysql_conn-8

@MrHorizonPy  Why does it not working?

**Comment by MrHorizonPy** [comment]
Hi I managed to go ahead but when I launch cmake --build build it returns all warnings and at the end an error visible in the screen below
![screen](https://github.com/DanielMartensson/GoobySoft/assets/132016637/bf4a7da2-172c-4ba6-a955-9e00ed6aaaa8)

**Comment by DanielMartensson** [comment]
> Hi I managed to go ahead but when I launch cmake --build build it returns all warnings and at the end an error visible in the screen below ![screen](https://private-user-images.githubusercontent.com/132016637/297438094-bf4a7da2-172c-4ba6-a955-9e00ed6aaaa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTg2MTAsIm5iZiI6MTcwNTUxODMxMCwicGF0aCI6Ii8xMzIwMTY2MzcvMjk3NDM4MDk0LWJmNGE3ZGEyLTE3MmMtNGJhNi1hOTU1LTllMDBlZDZhYWFhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxOTA1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzNkNDg0NGI2MzZlOTUwODk5Yzc2MDQyZDI3MmE2MTU3NTY5MzlhMGM5NjQ5YzliODgzZmI4OGQ3YzRkOTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rbn4Xmr1_pJ-AKc7wZABtX3aQNJ7jds9ncHW_gi5Zw0)

@MrHorizonPy 
You need Math Kernel Library from Intel. Easy to install.

**Comment by MrHorizonPy** [comment]
Hi, Intel MKL is not compatible for ARM64 platform, how can I proceed?

**Comment by DanielMartensson** [comment]
> Hi, Intel MKL is not compatible for ARM64 platform, how can I proceed?

@MrHorizonPy Disable MLK inside 
https://github.com/DanielMartensson/GoobySoft/blob/9359aaafa1e742234cf09b3a916cbf3f30192a25/GoobySoft/Tools/Software/Libraries/CControl/Headers/defines.h#L43-L44

Just place a comment //...or even better, send me a pull request were you disable #define MLK_USED if ARM64 is the target.
But you need to do that inside CControl repository. 

https://github.com/DanielMartensson/CControl/blob/master/src/CControl/Headers/defines.h

**Comment by MrHorizonPy** [comment]
I commented out the two lines, but now it gives this error:
![ERROR](https://github.com/DanielMartensson/GoobySoft/assets/132016637/f6125f9a-a80a-47d6-8510-8e1c3786e51b)

**Comment by DanielMartensson** [comment]
> I commented out the two lines, but now it gives this error: ![ERROR](https://private-user-images.githubusercontent.com/132016637/297748471-f6125f9a-a80a-47d6-8510-8e1c3786e51b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODY1ODcsIm5iZiI6MTcwNTU4NjI4NywicGF0aCI6Ii8xMzIwMTY2MzcvMjk3NzQ4NDcxLWY2MTI1ZjlhLWE4MGEtNDdkNi04NTEwLThlMWMzNzg2ZTUxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxMzU4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDE1ZmJjMGZkNzYxMGQxZDZhN2Q2ZmYxNzdlZmQ3NTFhY2MxNDBiY2RmNWQxMTAxMTg5YzcxYTIzYzVlNTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V0TXgGKEs3DCaVSsq_0NpTBDqZlDgPYrtPIYSelhpt8)

@MrHorizonPy 
Hi!

Use the pre-processor macro instead.
For example if `__aarch64__` or `__arm__` is not defined, then the `#defined MLK_USED...` should not be there.

You know what I'm talking about?

```c
/* Select library by uncomment - If non of these are uncomment, then CControl will use the internal library instead */
#if !defined(__aarch64__) && !defined(__arm__)
#define MKL_LAPACK_USED 				/* For large matrices on a regular computer */
#define MKL_FFT_USED					/* For large matrices on a regular computer */
#else
#define CLAPACK_USED   					/* For larger embedded systems */
#endif /* !defined(__aarch64__) && !defined(__arm__) */
```

**Comment by MrHorizonPy** [comment]
Hello @DanielMartensson, can you be more specific?
Being an ARM-based platform, I changed the defines.h like this:
```c++
#if defined(__aarch64__) || defined(__arm__)
#define CLAPACK_USED
#else
#define MKL_LAPACK_USED
#define MKL_FFT_USED
#endif
``` 
after making the change returns another error concerning a problem with the declaration of:
```c++
float atan2f(float)
``` 
I think there is a problem with the statements in the libraries. Can you give me a hand with this problem?

**Comment by DanielMartensson** [comment]
> Hello @DanielMartensson, can you be more specific? Being an ARM-based platform, I changed the defines.h like this:
> 
> ```c++
> #if defined(__aarch64__) || defined(__arm__)
> #define CLAPACK_USED
> #else
> #define MKL_LAPACK_USED
> #define MKL_FFT_USED
> #endif
> ```
> 
> after making the change returns another error concerning a problem with the declaration of:
> 
> ```c++
> float atan2f(float)
> ```
> 
> I think there is a problem with the statements in the libraries. Can you give me a hand with this problem?

@MrHorizonPy 

Yes, you need to add `#ifndef` or `#if` support for `__aarch64__` and `__arm__`.

Do you know how the pre-processor works? If your compiler have defined `__aarch64__`, then that word will be valid/defined inside CControl. 

https://github.com/DanielMartensson/CControl/blob/master/src/CControl/Headers/functions.h

**Comment by MrHorizonPy** [comment]
So @DanielMartensson , I modified **define.h** by implementing #if with the pre-processor macros **`__aarch64__`** and **`__arm__`**:
```c
#if !defined(__aarch64__) && !defined(__arm__)
#define MKL_LAPACK_USED 
#define MKL_FFT_USED					
#else
#define CLAPACK_USED   					
#endif 
``` 
and the error I attached in the last screenshot appeared, the one concerning the declaration of "**atan2f**" .
I'm stuck here and can't move forward

**Comment by DanielMartensson** [comment]
> So @DanielMartensson , I modified **define.h** by implementing #if with the pre-processor macros **`__aarch64__`** and **`__arm__`**:
> 
> ```c
> #if !defined(__aarch64__) && !defined(__arm__)
> #define MKL_LAPACK_USED 
> #define MKL_FFT_USED					
> #else
> #define CLAPACK_USED   					
> #endif 
> ```
> 
> and the error I attached in the last screenshot appeared, the one concerning the declaration of "**atan2f**" . I'm stuck here and can't move forward

@MrHorizonPy I will help you.

The reason why you get an error from `atan2f` is because your compiler have that already defined. The reason why I define `atan2f` is because `CControl` is written in `ANSI C` which is from `1989`, also called `C89`.

It's a long time support standard for `C`. 

The drawback with `C89` is that it only holds `atan2` and not `atan2f`. What you need to do is to add 

https://github.com/DanielMartensson/CControl/blob/479fec0abf1176b7c58d4ae3b32f4cee3c02b144/src/CControl/Headers/functions.h#L16-L17

```c
#ifndef _MSC_VER && ARM_COMPILER
INLINE float sqrtf(float x) {
```

.......by the way. Write this:
![image](https://github.com/DanielMartensson/GoobySoft/assets/28505229/aa0370d1-ea75-45e8-b31c-de8c86b8d2a8)

![image](https://github.com/DanielMartensson/GoobySoft/assets/28505229/cc672018-4e4b-4670-90c0-ee6323131be9)

![image](https://github.com/DanielMartensson/GoobySoft/assets/28505229/13d15ca3-d346-4367-910a-57d6ea97f1e3)


The reason why I don't do this for you, is because I want to to understand the power of macros =) 
Play around with your new macro `ARM_IS_USED`

**Comment by DanielMartensson** [comment]
@MrHorizonPy i have fixed it four you

**Comment by MrHorizonPy** [comment]
Hi @DanielMartensson, thanks for everything but it keeps giving me the error:
`mkl.h: no such file or directory.`

I modified `defines.h` and `functions.h` as you indicated above:

`defines.h`:
```c
#ifndef CCONTROL_HEADERS_DEFINES_H_
#define CCONTROL_HEADERS_DEFINES_H_

#ifndef __cplusplus
#ifndef __STDC_VERSION_
#define __STDC_VERSION_ 199409L
#endif

#if defined(__aarch64__) || defined(__arm__)
#define ARM_IS_USED
#endif
``` 

```c
#ifndef ARM_IS_USED
#define MKL_LAPACK_USED
#define MKL_FFT_USED
#else
#define CLAPACK_USED
#endif

#if defined(MKL_LAPACK_USED) || defined(MKL_FFT_USED)
#include <mkl.h>
#endif
``` 
`functions.h`:
```c
#if __STDC_VERSION___ < 199901L
#if !defined(_MSC_VER) || !defined(ARM_IS_USED)
float sqrtf(float x) {
            return (float)sqrt(x);
}
``` 

Also at the beginning of the compilation it returns many warnings, I will put an example below:
`cc1plus: warning: /home/ubuntu/GoobySoft/GoobySoft/Tools/Tools.h not a directory`

**Comment by DanielMartensson** [comment]
> Author

@MrHorizonPy I have updated the repository. Try to do a `pull` and run the make file. You need to learn how you can use macros. Try to ask Chat GPT for some examples how `#ifndef`, `#ifdef`, `#if`, `defined()` and `#define` works
